### ISSUE TITLE
Build Failure on Linux/aarch64 

### ISSUE THREAD

**Issue by danieldjewell** [facebookincubator/cargo-guppy#175]
Hello!

Build is failing on aarch64 (Android/Linux although I don't see that other aarch64 platforms would be different) because the ```CARGO_CFG_TARGET_FEATURE``` env variable is undefined. Presumably because there aren't any target features listed for aarch64 here: https://doc.rust-lang.org/reference/conditional-compilation.html#target_feature

https://github.com/facebookincubator/cargo-guppy/blob/b9dcb6b50419a2bb74981d98cddce4e7972f92f8/target-spec/build.rs#L14 

Running ```export CARGO_CFG_TARGET_FEATURE=''``` prior to ```cargo build``` seemed to make things work. It would appear that it is an incorrect assumption that this env var is *always* defined. 

### Version Info
| Program | Version |
|-|-|
| cargo | 1.45.1 |
| rustc | 1.45.2 |
| rustfmt | 1.4.17-stable (28bba61 2020-08-05) |
| rust-lldb | 10.0.1 |
| lld | 10.0.1 |
| cargo-guppy | b9dcb6b |

**Comment by sunshowers** [comment]
Thank you for the exceptional bug report! Going to see what I can do, I'd like to get CI going on aarch64.

**Comment by sunshowers** [comment]
@danieldjewell just published a new version of target-spec. I've managed to get CI to test cross-compiling on aarch64 but not running tests yet -- hope it works, and please let me know if you have any other issues! Thank you 💕
