### ISSUE TITLE
`filter` convenience method on `PackageSet`

### ISSUE THREAD

**Issue by inanna-malick** [facebookincubator/cargo-guppy#227]
from conversation with @sunshowers 

```
fn filter<F: FnMut(&PackageMetadata) -> bool>(&self, f: F) -> Self
```

This can be accomplished using `intersection`, but it would be great to have a convenience function for it

you could also add a `parfilter` function that uses `rayon`

**Comment by sunshowers** [comment]
It would be great to have this, and it is hopefully not very complex.
