### ISSUE TITLE
Determinator compiled failed on windows

### ISSUE THREAD

**Issue by fikgol** [facebookincubator/cargo-guppy#263]
PS C:\Users\fikgol\Workspaces\cargo-guppy\tools\determinator> cargo build
   Compiling determinator v0.2.0 (C:\Users\fikgol\Workspaces\cargo-guppy\tools\determinator)
error[E0433]: failed to resolve: could not find `unix` in `os`
   --> tools\determinator\src\paths0.rs:168:26
    |
168 |             use std::os::unix::ffi::OsStrExt;
    |                          ^^^^ could not find `unix` in `os`

error[E0599]: no function or associated item named `new_unix` found for struct `Paths0` in the current scope
  --> tools\determinator\src\paths0.rs:87:29
   |
67 | pub struct Paths0 {
   | ----------------- function or associated item `new_unix` not found for this
...
87 |             return Ok(Self::new_unix(buf));
   |                             ^^^^^^^^ function or associated item not found in `Paths0`

error[E0599]: no function or associated item named `new_unix` found for struct `Paths0` in the current scope
   --> tools\determinator\src\paths0.rs:104:29
    |
67  | pub struct Paths0 {
    | ----------------- function or associated item `new_unix` not found for this
...
104 |             return Ok(Self::new_unix(buf));
    |                             ^^^^^^^^ function or associated item not found in `Paths0`

error[E0599]: no function or associated item named `from_bytes` found for struct `OsStr` in the current scope
   --> tools\determinator\src\paths0.rs:173:50
    |
173 |                     .map(|path| Path::new(OsStr::from_bytes(path))),
    |                                                  ^^^^^^^^^^ function or associated item not found in `OsStr`

error: aborting due to 4 previous errors

**Comment by sunshowers** [comment]
Thank you!

I'm going to do a determinator release shortly with experimental Windows support. The tests pass but there may still be bugs lurking, would really appreciate a report :)

**Comment by sunshowers** [comment]
I've released new versions of the determinator and other crates, please let me know how it goes!

**Comment by sunshowers** [comment]
Going to close this in favor of #265 since the determinator now compiles on Windows and is tested in CI. Thanks again for reporting this issue :)
