### ISSUE TITLE
Guppy fails to run on combine-3.8.1

### ISSUE THREAD

**Issue by nasifimtiazohi** [facebookincubator/cargo-guppy#416]
When trying to run guppy on an older version of combine, [`combine 3.8.1`](https://github.com/Marwes/combine/tree/bdbcdfe1aebd6f49d9dfe0bfa0fef78752d26947),  guppy fails with below error:

> CommandError(CargoMetadata { stderr: "    Updating crates.io index\nerror: failed to select a version for the requirement `partial-io = \"=0.3.0\"`\ncandidate versions found which didn\'t match: 0.5.0, 0.4.0, 0.3.1\nlocation searched: crates.io index\nrequired by package `combine v3.8.1 (/private/var/folders/0d/58w3rsls6sjfrwhfrfyxhtym0000gn/T/.tmpPUg1q7/combine-source)`\n" })

The `Cargo.toml` file in this case declares `partial-io = { version = "0.3", features = ["tokio", "quickcheck"] }`. However, crates.io does not host any version below `1.0.0-beta2` which may be a reason for failure.

**Comment by sunshowers** [comment]
Yeah, the older versions `of` `partial-io` were removed. Please upgrade to a newer version.
