### ISSUE TITLE
Guppy fails with unknown target

### ISSUE THREAD

**Issue by nasifimtiazohi** [facebookincubator/cargo-guppy#419]
Guppy fails on project [solana ](https://github.com/solana-labs/solana) with below message:
`Error: Error while computing package graph: for package 'solana-merkle-tree 1.8.0 (path+file:///Users/nasifimtiaz/repos/solana/merkle-tree)': for dependency 'matches', parsing target 'bpfel-unknown-unknown' failed: unknown target triple: bpfel-unknown-unknown`

The relevant Cargo.toml from the project: https://github.com/solana-labs/solana/blob/5085f10b4cfa03dbffa5cf7d7e103bcd31f0bdc6/merkle-tree/Cargo.toml#L16-L19

**Comment by sunshowers** [comment]
I believe the cfg-expr version needs to be updated. Feel free to do so and release new guppy versions, or I might get around to it in the next few weeks.

**Comment by bmwill** [comment]
@sunshowers Yeah it looks like we may have to do a little tweaking since by default it looks like cfg-expr only handles builtin targets. We're also not in a huge rush to fix this, I was just ensuring that Nasif documented some of the issues he ran into prior to the end of his internship.

**Comment by sunshowers** [comment]
Yeah -- part of the problem is that our target selection code just can't process a target that it doesn't know about. One potential solution is to use targets from the current `rustc` version but that's a bit more work.

**Comment by bmwill** [comment]
It seems like [`target-lexicon`](https://docs.rs/target-lexicon/0.12.1/target_lexicon/) might be another option, although i'm not sure exactly what guppy expects out of the target information so that may not solve the problem.

**Comment by sunshowers** [comment]
That would run into the same problem (`target-lexicon` also has to keep its targets up to date e.g. https://github.com/bytecodealliance/target-lexicon/commit/fc20d683f186a36268cbb874c2b5986d516e0270) -- and we use the evaluator in `target-spec` so would have to write our own anyway.

**Comment by sunshowers** [comment]
(Also `target-spec` actually uses `target-lexicon` I believe)
