### ISSUE TITLE
Explicitly setting features to = default features doesn't resolve to the same feature set

### ISSUE THREAD

**Issue by carols10cents** [facebookincubator/cargo-guppy#510]
I'm not sure if this is intended behavior or not, but it wasn't what I expected.

## What happened

I have a minimal reproduction of the issue in this repo: https://github.com/integer32llc/hakari-repro

This repo is a workspace with 2 crates, "hello" and "world", and a workspace crate managed by cargo-hakari.

The "hello" crate depends on the `nom` crate with default features: https://github.com/integer32llc/hakari-repro/blob/67bbb10a43f78a707f67df10dd0c7b4791fba5c1/hello/Cargo.toml#L7

The "world" crate depends on the `nom` crate with default features off and the "std" feature enabled explicitly: https://github.com/integer32llc/hakari-repro/blob/67bbb10a43f78a707f67df10dd0c7b4791fba5c1/world/Cargo.toml#L7

Nom's default features are set to `std`, the same set that the "world" crate is setting explicitly: https://github.com/Geal/nom/blob/b6f79c4d375ae55e1fd1a35032ebb47a52ea3389/Cargo.toml#L32

When I ran `cargo hakari generate`, `nom` was added to the workspace-hack crate with `features = ["alloc", "std"]`: https://github.com/integer32llc/hakari-repro/blob/67bbb10a43f78a707f67df10dd0c7b4791fba5c1/workspace-hack/Cargo.toml#L16

## What I expected

Because nom's default feature set resolves to the same set of features chosen explicitly by the "world" crate, I expected cargo-hakari to figure that out and not include "nom" in the workspace-hack crate. 

Maybe the "default" feature set is just considered to be a different feature set than an explicit feature set that happens to be the same, though? Or maybe I'm misunderstanding something about feature resolution or how cargo-hakari is expected to work? 

Thanks!!

**Comment by sunshowers** [comment]
> Maybe the "default" feature set is just considered to be a different feature set than an explicit feature set that happens to be the same, though? Or maybe I'm misunderstanding something about feature resolution or how cargo-hakari is expected to work?

Yeah, nom has a separate feature called "default", and the feature set {"default", "std"} is treated differently from the feature set {"std"} by Cargo (and therefore hakari). In particular, you can theoretically gate code on `#[cfg(feature = "default")]` (it's not common to do so but hakari doesn't make that assumption)

**Comment by sunshowers** [comment]
I think this is sufficiently answered, happy to answer follow-up questions but I do believe hakari is behaving correctly here!
