### ISSUE TITLE
`cargo guppy resolve-cargo` fails due to invalid `--initials-platform` argument parsing

### ISSUE THREAD

**Issue by psFried** [facebookincubator/cargo-guppy#602]
I just tried out `cargo guppy` and found that running `cargo guppy resolve-cargo` fails with the following error:

```
error: "standard" isn't a valid value for '--initials-platform <INITIALS_PLATFORM>'
	[possible values: v1, v1-install, v2]

USAGE:
    cargo-guppy resolve-cargo [OPTIONS]

For more information try --help
```

This seems to be caused by [this line](https://github.com/facebookincubator/cargo-guppy/blob/17329f7bddd47d24064d4f88570d3592db42fb37/guppy-cmdlib/src/lib.rs#L110), which incorrectly references `ResolverVersion` when configuring the allowable values.

**Comment by sunshowers** [comment]
Thanks for reporting this! Fix coming up in just a bit.
