### ISSUE TITLE
`depends_on()` doesn't work as expected.

### ISSUE THREAD

**Issue by Guiguiprim** [facebookincubator/cargo-guppy#632]
It looks like `depends_on()` doesn't work as expected.

See https://github.com/facebookincubator/cargo-guppy/pull/631

**Comment by sunshowers** [comment]
#631 doesn't look like a bug, but I wouldn't be surprised if there's some other sort of bug lurking somewhere.

**Comment by Guiguiprim** [comment]
I changed my test: https://github.com/facebookincubator/cargo-guppy/pull/634

This one I'm sure it should pass.

**Comment by Guiguiprim** [comment]
Apparently I'm just not capturing the metadata the right way, sorry for the inconvenience.
