### ISSUE TITLE
generate workspace dependencies

### ISSUE THREAD

**Issue by xxchan** [facebookincubator/cargo-guppy#675]
Cargo now supports specify `workspace.dependencies`. Is it possible for `cargo-hakari` to generate `workspace.dependencies` so that `workspace-hack` isn't needed anymore? 🤔

https://blog.rust-lang.org/2022/09/22/Rust-1.64.0.html#cargo-improvements-workspace-inheritance-and-multi-target-builds

**Comment by sunshowers** [comment]
Hi -- I've left Meta and can no longer contribute to this repository. Please file an issue at https://github.com/guppy-rs/guppy. Thanks.
